#pragma once
#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <random>
#include <vector>
#include <fstream>
#include <sstream>
#include <cstdlib>
#include <chrono>

using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::setprecision;
using std::string;
using std::copy;
using std::vector;
using std::fixed;
using std::ifstream;
using std::stoi;
using std::getline;
using std::cerr;
using std::ofstream;